Style/StringLiterals:
  EnforcedStyle: single_quotes
InlineComment:
  Enabled: false
java_script:
  enabled: false
  config_file: config/jshint.json
ruby:
  enabled: false
  config_file: config/rubocup.yml
scss:
  enabled: false
