language: ruby
rvm:
- 2.3.3
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database farmbot_test'
  - psql -c 'create database farmbot_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
script: "bundle exec rspec spec/"
env:
# A 'fake' secret token for use in our CI env.
# Don't worry- this isn't the real one.
  - SECRET_TOKEN=e815982094c62436066bafc9151f2d33c4a351a776654cb7487476de260a4592
  - MQTT_HOST=blooper.io
  - OS_UPDATE_SERVER=http://blah.com
  - FW_UPDATE_SERVER=http://test.com
  - DB=postgresql