version: '3.4'
x-db_user: &db_user
  depends_on: ["db"]
x-rails: &rails
  image:    farmbot_web
  env_file: .env
  volumes:
    - .:/farmbot
    - ./docker_volumes/bundle_cache:/bundle
services:
  redis:
    image: redis:4.0.11
    environment: ["REDIS_PASS=mypass"]
    ports:       ["6379:6379"]
  db:          # ====================
    image: postgres
    volumes: ["./docker_volumes/db:/var/lib/postgresql/data"]
    env_file: .env
  web:         # ====================
    <<: *db_user
    <<: *rails
    build:
      context: .
      dockerfile: docker_configs/api.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e development -p 3000 -b 0.0.0.0"
    ports: ["3000:3000"] # Web / API
  mqtt:        # ====================
    build:
      context: ./docker_configs
      dockerfile: rabbitmq.Dockerfile
    ports:
     - "5672:5672"   # AMQP (RabbitMQ)
     - "1883:1883"   # MQTT
     - "8883:8883"   # MQTT over TLS/SSL
     - "3002:15675"  # MQTT over WebSockets
     - "15672:15672" # Management API
    depends_on: ["web"]
    env_file:   .env
    environment:
     - RABBITMQ_CONFIG_FILE=/farmbot/farmbot_rmq_config
    volumes:
     - ./docker_volumes/rabbit:/farmbot
  webpack:     # ====================
    <<: *rails
    command: ./node_modules/.bin/webpack-dev-server --config config/webpack.config.js
    ports: ["3808:3808"] # Webpack Dev Server
  delayed_job: # ====================
    <<: *rails
    depends_on: ["db","mqtt"]
    command: bundle exec rake jobs:work
  log_digests: # ====================
    <<: *rails
    <<: *db_user
    command: bundle exec rake api:log_digest
  rabbit_jobs: # ====================
    <<: *rails
    depends_on: ["db","mqtt"]
    command: bundle exec rails r lib/rabbit_workers.rb
