version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./docker_volumes/db:/var/lib/postgresql/data
    env_file:
      - ./.env
  mqtt:
    build: ./mqtt
    ports:
     - "5672:5672"   # AMQP (RabbitMQ)
     - "1883:1883"   # MQTT
     - "8883:8883"   # MQTT over TLS/SSL
     - "3002:15675"  # MQTT over WebSockets
     - "15672:15672" # Management API
  web:
    build:
      context: .
      dockerfile: docker-api.Dockerfile
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: bundle exec rails api:start
    volumes:
      - .:/farmbot
    ports:
      - "3000:3000" # Web / API
      - "3808:3808" # Webpack Dev Server
    depends_on:
      - db
    env_file:
      - ./.env
