version: 2
# executor: "machine"
jobs:
  build:
    executor: "machine"
    steps:
      - checkout
      - run:
          name: Do stuff - Part I
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > docker-compose
            chmod +x docker-compose
            sudo mv docker-compose /usr/local/bin
            mv travis.env .env
            sudo docker-compose run web bundle install
            sudo docker-compose run web npm install
            sudo docker-compose run web bundle exec rails db:setup
            sudo docker-compose run web rake keys:generate
      - run:
          name: Do stuff - Part II
          command: |
            sudo docker-compose run -e COVERALLS_REPO_TOKEN=lEX6nkql7y2YFCcIXVq5ORvdvMtYzfZdG web rspec spec
            sudo docker-compose run webpack sh run_js_build.sh
      - deploy:
          name: Build and push Docker image
          command: |
            echo "Tada!"
