default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: farmbot_development

test:
  <<: *default
  database: farmbot_test

production:
  <<: *default
  database: farmbot_prod
