default: &default
  adapter: mysql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: farmbot_api_dev
  password: "password123"

test:
  <<: *default
  database: farmbot_api_test
  password: "password123"

production:
  <<: *default
  database: farmbot_api_dev
  password: "password123"
