development:
  sessions:
    default:
      database: dss_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: dss_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      uri: mongodb://00-default:cFdZV2ZKYUdUSm1aaEswZFlBTm4vTW1HWGhXdVJOek9QT0NveVdQNVc3WT0K@172.17.0.27:27017/farmbot-production
